// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbggubfobfawsoornjoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZ2d1YmZvYmZhd3Nvb3Juam9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjIxMDksImV4cCI6MjA3MDkzODEwOX0.Fru1CPHxMaywHf-fhzSxQ_E2u7PF3VyRoza2JeMvr3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});